### PR TITLE
SWITCHYARD-2603  Exception BRMS Karaf tests

### PR DESCRIPTION
**Pull request by dvirgiln**
https://issues.jboss.org/browse/SWITCHYARD-2603

### CODE REVIEW

**Comment by cunningt** [comment]
@dvirgiln : This seems to cause a build failure when I do 
mvn -Peap,karaf,brms -Deap.home=/Users/cunningt/jboss-eap-6.4 clean install

**Comment by dvirgiln** [comment]
could you include the trace log, included in the target/surefire-reports

Include one file, for example the org.switchyard.karaf.test.quickstarts.BPMServiceQuickstartTest.txt

I have a suspicious here. Yesterday in the fuse-bxms-integ repo I started having some error in the tests (without having made any change), related the activation of the switchyard bundle.

**Comment by cunningt** [comment]
@dvirgiln Logged SWITCHYARD-2618 with all the information.    It looks like a similar issue to what's intended to be fixed here.

**Comment by dvirgiln** [comment]
Hi Tom, I ve updated all the repos of 2.x, build and compile release. This is the result:

Remember this goes to 2.x.

[INFO] Reactor Summary:
[INFO] 
[INFO] SwitchYard: BRMS: Karaf ........................... SUCCESS [0.905s]
[INFO] SwitchYard: Karaf Features ........................ SUCCESS [0.160s]
[INFO] SwitchYard: Karaf Tests ........................... SUCCESS [2:51.387s]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 2:53.364s
[INFO] Finished at: Fri Mar 20 12:30:01 CET 2015

**Pull request closed without merging**
